## NumPy and Pandas Exercises  Exercises 

Question 1 a) Generate a 2 by 3 matrix containing elements from 1 to 6 and multiply it by a scalar of two.

Solution:

In [59]:
import numpy as np

A = np.arange(1, 7).reshape((2, 3))

A_by_scalar = A * 2

print(A_by_scalar)



[[ 2  4  6]
 [ 8 10 12]]


Question 1 b) Create a 3 by 3 identity matrix


Solution:

In [84]:
I = np.identity(3)

print(I)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Question 1 c) Create a 1-D array call arry1 which contains elements ranging from zero to twenty-seven. Convert arry1 to a 3-D arry2

Solution:

In [85]:
arry1 = np.arange(0, 27) # a 3-D array can not be created out of 28 element so I used 27

arry2 = arry1.reshape((3, 9))

print(arry2)


[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]]


Question 1 d) Create two 2-D arrays with the first array containing elements from 1 to 6 and the second array containing elements from 7 to 12.
             Horizontally stack the two arrays together. Using the same set of arrays vertically stack the two arrays

Solution:

In [86]:
x = np.arange(1, 7).reshape((2, 3))

print('X =',(x))

y = np.arange(7, 13).reshape((2, 3))

print('Y =',(y)) 

X = [[1 2 3]
 [4 5 6]]
Y = [[ 7  8  9]
 [10 11 12]]


In [87]:
horizontal_stack = np.hstack((x, y))

print(horizontal_stack)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [88]:
vertical_stack = np.vstack((x, y))

print(vertical_stack)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Question 1 e) Create an equally spaced sequence with a gap of 5 ranging from 0 to 100

Solution:

In [89]:
seq_5 = np.arange(0, 101, 5)

print(seq_5)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]


Question 2 a) Create a DataFrame named as students using a list of names of 5 students

Solution:

In [90]:
import pandas as pd

students = pd.DataFrame(['Anderson', 'Samuel', 'Wisdom', 'Clement', 'Stephen'], columns=['Name'])

print(students)

       Name
0  Anderson
1    Samuel
2    Wisdom
3   Clement
4   Stephen


Question 1 b) Write a program to create a DataFrame teams using a list of names of Ghana Premier League Teams and the goals they scored in their previous five matches

Solution:

In [91]:


Data = {'Team': ['Accra Hearts of Oak', 'Asante Kotoko', 'Ebusua Dwarfs', 'Sekondi Hassacas', 'Okwahu United', 'Tano Bofoakwa', 'BA United'],
                      'TG': [10, 7, 5, 8, 9, 6, 5],
                      'Match 1': [2, 1, 1, 1, 2, 0, 1],
                      'Match 2': [1, 1, 1, 2, 2, 1, 2],
                      'Match 3': [3, 1, 0, 3, 1, 2, 0],
                      'Match 4': [2, 3, 1, 0, 2, 2, 1],
                      'Match 5': [2, 2, 2, 2, 2, 1, 1]}
Teams = pd.DataFrame(Data)
print(Teams)

                  Team  TG  Match 1  Match 2  Match 3  Match 4  Match 5
0  Accra Hearts of Oak  10        2        1        3        2        2
1        Asante Kotoko   7        1        1        1        3        2
2        Ebusua Dwarfs   5        1        1        0        1        2
3     Sekondi Hassacas   8        1        2        3        0        2
4        Okwahu United   9        2        2        1        2        2
5        Tano Bofoakwa   6        0        1        2        2        1
6            BA United   5        1        2        0        1        1


Question 2 c) Write a program to create a DataFrame countries using a dictionary which stored country name, capitals, and populations of the country. Do this for West African Countries.

Solution:

In [92]:
countries_data = {'Country': ['Nigeria', 'Ghana', 'Ivory Coast', 'Liberia', 'Sierra Leone', 'Togo'],
                  'Capital': ['Abuja', 'Accra', 'Yamoussoukro', 'Monrovia', 'Freetown', 'Leome'],
                  'Population(in million)': [200.9, 31.1, 25.7, 4.9, 7.8, 8.6]}

countries = pd.DataFrame(countries_data)

print(countries)

        Country       Capital  Population(in million)
0       Nigeria         Abuja                   200.9
1         Ghana         Accra                    31.1
2   Ivory Coast  Yamoussoukro                    25.7
3       Liberia      Monrovia                     4.9
4  Sierra Leone      Freetown                     7.8
5          Togo         Leome                     8.6


Question 2 d) Consider the following data and write a programme to capture the data in python.
i) Print the Team name along with Goals For (GF), Goals Against (GA) and Points (PTS).

Solution:

In [93]:
data = {'Team': ['Hearts of Oak', 'Asante Kotoko', 'Ebusua Dwarfs', 'Sekondi Hassacas', 'Okwahu United', 'Tano Bofoakwa', 'BA United'],
    'GF': [120, 90, 90, 80, 78, 70, 71],
    'GA': [35, 55, 60, 43, 39, 50, 55],
    'PTS': [80, 60, 60, 55, 53, 49, 44]}

df = pd.DataFrame(data, index=[1, 2, 3, 4, 5, 6, 7])

print(df)

               Team   GF  GA  PTS
1     Hearts of Oak  120  35   80
2     Asante Kotoko   90  55   60
3     Ebusua Dwarfs   90  60   60
4  Sekondi Hassacas   80  43   55
5     Okwahu United   78  39   53
6     Tano Bofoakwa   70  50   49
7         BA United   71  55   44


Question 2 dii) Display details of the team that considered more than 30 goals


Solution:

In [94]:
more_than_30 = df[df['GA'] > 30]

print(more_than_30)


               Team   GF  GA  PTS
1     Hearts of Oak  120  35   80
2     Asante Kotoko   90  55   60
3     Ebusua Dwarfs   90  60   60
4  Sekondi Hassacas   80  43   55
5     Okwahu United   78  39   53
6     Tano Bofoakwa   70  50   49
7         BA United   71  55   44


Display details of the team that scored less than 80 goals

Solution:

In [95]:
less_than_80 = df[df['GF'] < 80]

print(less_than_80)

            Team  GF  GA  PTS
5  Okwahu United  78  39   53
6  Tano Bofoakwa  70  50   49
7      BA United  71  55   44


Display details of the team that had less than 60 points


Solution:

In [96]:
less_than_60 = df[df['PTS'] < 60]

print(less_than_60)

               Team  GF  GA  PTS
4  Sekondi Hassacas  80  43   55
5     Okwahu United  78  39   53
6     Tano Bofoakwa  70  50   49
7         BA United  71  55   44
